### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by nexus** [pmneo/ts-importer#3]
Please add support for import of namespace. Currently it imports a class but it is not visible without importing namespace.

**Comment by pmneo** [comment]
Adding namespace support is very tricky, because this requires an advanced parsing of the source files. 
Besides that, please provide a sample project with an expectation example.

**Comment by pmneo** [comment]
No sample, no further actions.

**Comment by micnic** [comment]
Hello @pmneo, I have the following usecase

I use React for a TS project and while minifying the expressions `React.createElement` is quite long, I created first a class named `R` to include some some shortcuts to the React methods and classes, but then I needed to use types and had to add a namespace instead of the class to be able to export types, example of the namespace:
```ts
import * as React from 'react';
import * as ReactDOM from 'react-dom';

export namespace R {

    export type Element = React.ReactElement<any>;
    export type MouseEvent = React.MouseEvent<any>;
    export type TouchEvent = React.TouchEvent<any>;

    export const clone = React.cloneElement;
    export const create = React.createElement;
    export const find = ReactDOM.findDOMNode;
    export const render = ReactDOM.render;
    export const unmount = ReactDOM.unmountComponentAtNode;

    export const Component = class <P, S> extends React.PureComponent<P, S> { };
    export const Stateless = class <P> extends R.Component<P, null> { };
    export const Base = class extends R.Stateless<null> { };
}
```
