### ISSUE TITLE
Option to prefer "barrel" (index.ts) files if available

### ISSUE THREAD

**Issue by JohannesRudolph** [pmneo/ts-importer#8]
Thanks so much for this awesome plugin! Couldn't live without it. 

Would it be possible to add an option to prefer an export from an `index.ts` file if it's available? This way it ts-importer could help me keep imports a lot cleaner. This is a common use case when dealing with angular2 modules for example.

**Comment by pmneo** [comment]
Am 24.10.2016 um 17:46 schrieb Johannes Rudolph:

**Comment by frederikschubert** [comment]
https://github.com/frederikschubert/ts-importer-barrel-import-example

@pmneo I hope this can help you!

**Comment by pmneo** [comment]
Thanks for your example. 

The biggest problem is, that i am parsing the source files by hand and do not use the typescript api because of performance. 

To support your feature, i have to follow up such an export / import statement to collect the symbols.

I will take a look into it, but it will be hard work to implement this.

**Comment by pmneo** [comment]
This will not be implemented
